language: nodejs
node_js:
  - '6'
  - '8'
  - 'stable'

services:
  - mysql

cache:
  directories:
  - "node_modules"

before_script:
  - mysql -e 'CREATE DATABASE test_db;'
  - mysql -e "GRANT ALL PRIVILEGES ON test_db.* TO 'test_db_user'@'localhost' IDENTIFIED BY 'secret_password'"

after_success: npm run coverage
